export const USER_DATA_REQUESTED = '@HOME/USER_DATA_REQUESTED';
export const USER_DATA_FETCH_SUCCEEDED = '@HOME/USER_DATA_FETCH_SUCCEEDED';
export const USER_DATA_FETCH_FAILED = '@HOME/USER_DATA_FETCH_FAILED';
